# Generated by Django 4.2.30 on 2026-06-15 19:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(25000)], verbose_name='amount being paid')),
                ('phone_number', models.CharField(max_length=40, verbose_name='phone number of person paying')),
                ('email', models.CharField(max_length=40, verbose_name='email of person paying')),
                ('full_name', models.CharField(max_length=50, verbose_name='full name of person paying')),
                ('payment_method', models.CharField(choices=[('CARD', 'card'), ('BANK', 'bank transfer'), ('MOMO', 'momo')], default='MOMO', max_length=10)),
                ('currency', models.CharField(choices=[('GHS', 'GHS')], default='GHS', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('payload_hash', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('COMPLETED', 'completed'), ('FAILED', 'failed')], default='COMPLETED', max_length=10)),
            ],
        ),
    ]
