# Generated by Django 4.2.30 on 2026-06-16 04:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CircuitBreakerState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('CLOSED', 'closed'), ('OPEN', 'open'), ('HALF_OPEN', 'half-open')], default='CLOSED', max_length=10)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('window_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
